const std = @import("std");
//intiial opcode plan
//impl.zig: inline function for every opcode mnemonic, so implementation is easier
//cpu.zig: the cpu just has a big switch statement generated by a script, that calls the functions
//so basically decoding is handled by the script and passed to the impl zig file
pub fn main() void {
    std.debug.print("hello. \n", .{});
}
